//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voos.WebServiceVoos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:55069/", ConfigurationName="WebServiceVoos.WebServiceVoosSoap")]
    public interface WebServiceVoosSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento LerVoosResult no namespace http://localhost:55069/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:55069/LerVoos", ReplyAction="*")]
        Voos.WebServiceVoos.LerVoosResponse LerVoos(Voos.WebServiceVoos.LerVoosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:55069/LerVoos", ReplyAction="*")]
        System.Threading.Tasks.Task<Voos.WebServiceVoos.LerVoosResponse> LerVoosAsync(Voos.WebServiceVoos.LerVoosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LerVoosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LerVoos", Namespace="http://localhost:55069/", Order=0)]
        public Voos.WebServiceVoos.LerVoosRequestBody Body;
        
        public LerVoosRequest() {
        }
        
        public LerVoosRequest(Voos.WebServiceVoos.LerVoosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LerVoosRequestBody {
        
        public LerVoosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LerVoosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LerVoosResponse", Namespace="http://localhost:55069/", Order=0)]
        public Voos.WebServiceVoos.LerVoosResponseBody Body;
        
        public LerVoosResponse() {
        }
        
        public LerVoosResponse(Voos.WebServiceVoos.LerVoosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:55069/")]
    public partial class LerVoosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LerVoosResult;
        
        public LerVoosResponseBody() {
        }
        
        public LerVoosResponseBody(string LerVoosResult) {
            this.LerVoosResult = LerVoosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceVoosSoapChannel : Voos.WebServiceVoos.WebServiceVoosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceVoosSoapClient : System.ServiceModel.ClientBase<Voos.WebServiceVoos.WebServiceVoosSoap>, Voos.WebServiceVoos.WebServiceVoosSoap {
        
        public WebServiceVoosSoapClient() {
        }
        
        public WebServiceVoosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceVoosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVoosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVoosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Voos.WebServiceVoos.LerVoosResponse Voos.WebServiceVoos.WebServiceVoosSoap.LerVoos(Voos.WebServiceVoos.LerVoosRequest request) {
            return base.Channel.LerVoos(request);
        }
        
        public string LerVoos() {
            Voos.WebServiceVoos.LerVoosRequest inValue = new Voos.WebServiceVoos.LerVoosRequest();
            inValue.Body = new Voos.WebServiceVoos.LerVoosRequestBody();
            Voos.WebServiceVoos.LerVoosResponse retVal = ((Voos.WebServiceVoos.WebServiceVoosSoap)(this)).LerVoos(inValue);
            return retVal.Body.LerVoosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Voos.WebServiceVoos.LerVoosResponse> Voos.WebServiceVoos.WebServiceVoosSoap.LerVoosAsync(Voos.WebServiceVoos.LerVoosRequest request) {
            return base.Channel.LerVoosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Voos.WebServiceVoos.LerVoosResponse> LerVoosAsync() {
            Voos.WebServiceVoos.LerVoosRequest inValue = new Voos.WebServiceVoos.LerVoosRequest();
            inValue.Body = new Voos.WebServiceVoos.LerVoosRequestBody();
            return ((Voos.WebServiceVoos.WebServiceVoosSoap)(this)).LerVoosAsync(inValue);
        }
    }
}
